### ISSUE TITLE
commit-message-validator doesn't work with husky

### ISSUE THREAD

**Issue by OneShiv** [banyudu/commit-message-validator#1]
With latest version of husky and commit message validator 
`{
  "name": "husky-try",
  "version": "1.0.0",
  "description": "",
  "main": "src/index.js",
  "scripts": {
    "prepare":"husky install",
    "test": "echo 'test'"
  },
  "devDependencies": {
    "husky": "7.0.2",
    "commit-message-validator": "1.0.0"
  },
  "keywords": [],
  "husky": {
    "hooks": {
      "commit-msg": "commit-message-validator"
    }
  },
  "config": {
    "commit-message-validator": {
      "_comment": "Pattern can be Regex string or array of Regex string",
      "pattern": "<pattern>",
      "errorMessage": "  \n\n❌  Your commit message is invalid. Please author your commit in the following pattern:<pattern>"
    }
  }
}
`
pre-commit hooks don't work.

**Comment by banyudu** [comment]
@OneShiv Husky 7 introduced a [breaking API](https://typicode.github.io/husky/#/?id=migrate-from-v4-to-v7) and does not read configs from package.json anymore.

You can setup husky hooks with this command:

```bash
npx husky add .husky/commit-msg "npx commit-message-validator"
```
which generates a `.husky/commit-msg` file with following content:

```bash
#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

npx commit-message-validator

```
